### PR TITLE
Split CLIs

### PR DESCRIPTION
**Pull request by ppoliani**
Fixes https://github.com/sigma0-xyz/zkbitcoin/issues/13

The following changes were applied:

1. Create a Cargo workspace
2. Split the current code base into three distinct crates
- `zkbitcoin-core`: Lib crate that contains common code used by the CLI binaris
- `zkbtc`: The CLI used by users 
- `zkbtc-admin`: CLI used for admin tasks

### CODE REVIEW

**Comment by mimoo** [comment]
Hey! Thanks for the PR. I'm a bit mixed about merging it because I think it's doing too much and at this point we haven't really talked about a reorganization of crates or why we should do this. Do you mind just having a PR that creates an additional zkbtc-admin bin?

**Comment by ppoliani** [comment]
@mimoo I could add just one more crate, still we would need to create a Cargo workspace the way it's done in this PR. The other thing is that we might end up with cyclic dependencies if we have just two crates. This is is pretty much a common crate organization where common code just goes to a separate crate to avoid potential cyclic dependencies.

**Comment by mimoo** [comment]
but why add one more crate? We can have different binaries in the current bin/ directory while keeping the same organization :o

**Comment by ppoliani** [comment]
Yes we can keep things in one single crate. Mixing things would violate SRP. While this might not look very important at the moment, it might bite us back once the codebase grows, and at that point it might be more challenging to split the code inot disitnct logical units.

In general, following the workspace solution is a common practise when building bigger Rust projects (with the potential to grow). I do though understand where you're coming from; so I can understand if you don't want to make any such changes at this point.

**Comment by mimoo** [comment]
let's keep everything in a single crate for now if you don't mind, sorry for the push back!

**Comment by ppoliani** [comment]
> let's keep everything in a single crate for now if you don't mind, sorry for the push back!

No worries at all :) Will do the split in the same crate

**Comment by ppoliani** [comment]
@mimoo closing this in favour of https://github.com/sigma0-xyz/zkbitcoin/pull/31

**Comment by ppoliani** [comment]
@mimoo closing this in favour of https://github.com/sigma0-xyz/zkbitcoin/pull/31

**Pull request closed without merging**
